### ISSUE TITLE
Draw card can draw itself

### ISSUE THREAD

**Issue by Turtyo** [Saplings-Projects/1M_sub#31] opened 2023-12-21 02:37 UTC
## Describe the bug
If the number of cards you have in your draw and discard pile combined is inferior to the number of card that the draw will take, then the draw card that you used will draw itself.

## To Reproduce
Steps to reproduce the behavior (an example with only 4 cards in hand)
1. Play a card (not the draw card)
2. You now have 1 in discard pile and 0 in draw
3. Play the draw 2 card
4. Since the draw is empty, the discard get put in the draw, and you get the card
5. Then you will get the draw card that you just played
6. Note that this also works if you directly play the draw card

## Expected behavior
You shouldn't be able to draw the card that makes you draw

## Screenshots
In chronological order (will try to take a video next time)

![gscreenshot_2023-12-21-033445](https://github.com/Saplings-Projects/1M_sub/assets/49365680/8d6e5b53-0e7e-418c-8ca6-98b9249f19ce)
![gscreenshot_2023-12-21-033452](https://github.com/Saplings-Projects/1M_sub/assets/49365680/2e0749b5-3db0-46ad-b0a6-a147895487c7)
![gscreenshot_2023-12-21-033455](https://github.com/Saplings-Projects/1M_sub/assets/49365680/756e5caa-afe6-461b-a8c8-0240cd3f64f8)
![gscreenshot_2023-12-21-033502](https://github.com/Saplings-Projects/1M_sub/assets/49365680/64b55c7a-63bf-46d9-badd-e3e5650289de)
![gscreenshot_2023-12-21-033505](https://github.com/Saplings-Projects/1M_sub/assets/49365680/63e48165-f148-4f61-924f-bb7cfc0969f7)
![gscreenshot_2023-12-21-033510](https://github.com/Saplings-Projects/1M_sub/assets/49365680/bba52930-6a14-4df6-b370-e7017627093d)

## Additional context
Might have to do with the order in which actions are taken (effect before discard or after).

**Comment by cheesefrycook** [comment] 2023-12-21 14:47
This makes sense with how the system works currently. I guess we can add a special check to never draw the card you just played from a draw action?

**Comment by cheesefrycook** [comment] 2023-12-21 14:49
Or maybe we need to change up the ordering of actions. Right now the played card gets discarded before drawing more cards

**Comment by Turtyo** [comment] 2023-12-21 20:45
Sure it makes sense with the structure, but i don't think that's how it should be
Maybe we should apply the effect before the discard
What was the issue with having the effects before the discard btw ?

**Comment by cheesefrycook** [comment] 2023-12-21 21:33
Say you’re at the max hand limit of 10 cards. Then you play a “draw 2” card. What should happen is you play the card and discard, then it draws back up to the max of 10. If we don’t make the card discard first, then the currently active card gets considered in the max hand limit, so you’ll only have 9 cards after you play the card

**Comment by Turtyo** [comment] 2023-12-21 21:39
This shouldn't be an issue anymore with @Tysterman74 change with active card. When a card becomes active, we remove if from the hand count, that way it doesn't block new cards from coming in the hand. That way we can also discard after effects are played, which might also solve the problem of having to delay certain things with a timer (since we know when the timer ends now, when the card is discarded).

**Comment by Tysterman74** [comment] 2024-01-17 04:09
https://github.com/Saplings-Projects/1M_sub/assets/5923102/cad7195b-89fa-4901-9640-0b0304c231ee

Looks like the Draw Card still is drawing itself. Although if enough cards are played then it won't come up. This feels like this would be by design.

**Comment by Tysterman74** [comment] 2024-01-17 04:24
I'll assign this to me for now, and if we want to fix this I can take a stab at it!

**Comment by Turtyo** [comment] 2024-01-17 23:40
Well yes technically given the code, this is working as the code intends, but not as we would intend.
Instead of a special check (because you could have more side effects like that, putting a check is not really fixing the underlying issue), we could make use of the active card that was discussed before:
a card is active when its effects are being applied:
- it is not counted in the hand anymore
- it is not yet counted in the discard pile

**Comment by Turtyo** [comment] 2024-01-18 01:40
Do you think this could work @Tysterman74 or do you have another idea to deal with the problem ?

**Comment by Tysterman74** [comment] 2024-01-18 01:51
I can investigate as part of this issue. But if it does seem to be a game loop issue that solution may work!

**Closed** 2024-01-26 21:03 UTC
Labels: bug, confirmed
